spring.application.name=meetelligence

server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/meetelligencedb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:password}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

groq.api.key=${GROQ_API_KEY:PASTE_YOU_GROQ_API_KEY_HERE_OR_CREATE_A_SYSTEM_VARIABLE}

auth.jwt.ttl=86400000

# KEEP ROTATING YOU SECRET FOR SECURITY
auth.jwt.secretKey=${JWT_SECRET:Y4Vw6n9kTzJ8mP2sR7xNq3LfA8bH5dKeU1wCjG0yZrM=}

discord.server.webhook.url=${DISCORD_WEBHOOK_URL:PASTE_YOUR_DISCORD_WEBHOOK_URL_HERE    }


